alg_name: "FT"
model_name: "<path_to_Meta-Llama-3-8B-Instruct>"
device: 0

layers: [<layer>]
num_steps: <num_steps>
batch_size: <batch_size>
max_length: <max_length>
lr: <lr>
weight_decay: <weight_decay>
kl_factor: <kl_factor>
norm_constraint: false

objective_optimization: "prompt_last"
rewrite_module_tmp: "model.layers.{}.mlp.down_proj.weight"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
model_parallel: false
